=== enrico4students/didattica_xml_json_etc/TPSIT-5o/hoepli_htdocs/hoepli/xml/catalogo.dtd
<!ELEMENT Catalogo (Film*) >
  <!ELEMENT Titolo (#PCDATA)>
  <!ELEMENT Regista (#PCDATA)>
  <!ELEMENT Attore (#PCDATA)>
  <!ELEMENT Genere (#PCDATA)>
  <!ELEMENT Film (Titolo,Regista+,Attore*,Genere?)>
  <!ATTLIST Film cod ID #REQUIRED
    originale (si|no) #IMPLIED 
    formato (VHS|DVD|DIVX) #REQUIRED
    voto CDATA #IMPLIED>

=== enrico4students/didattica_xml_json_etc/TPSIT-5o/hoepli_htdocs/hoepli/xml/catalogo.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Catalogo SYSTEM "catalogo.dtd">
<Catalogo>
<Film cod="f1" formato="DVD" voto="10">
<Titolo>Bohemian Rhapsody</Titolo>
<Regista>Bryan Singer,</Regista>
<Attore>Rami Malek</Attore>
<Attore>Lucy Boynton</Attore>
<Attore>Gwilym Lee</Attore>
<Genere>Musicale</Genere>
</Film>
<Film cod="f2" formato="DIVX">
<Titolo>Fantasia</Titolo>
<Regista> Samuel Armstrong</Regista>
<Genere>Animazione</Genere>
<originale>si</originale>
</Film>
</Catalogo>
